---
# VaultDynamicSecret fetches dynamic database credentials from Vault
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: scheduling-service-db-creds
  namespace: whispr-prod
spec:
  vaultAuthRef: scheduling-service-vault-auth
  mount: database
  path: creds/role_scheduling_service
  destination:
    create: true
    name: scheduling-service-db-secret
  rolloutRestartTargets:
    - kind: Deployment
      name: scheduling-service
  renewalPercent: 67
  revoke: true
