apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-service-config
  namespace: whispr-prod
  labels:
    app.kubernetes.io/name: messaging-service
data:
  MIX_ENV: "prod"
  PHX_SERVER: "true"
  PHX_HOST: "whispr.fr"
  PORT: "4000"
  GRPC_PORT: "4001"
  LOG_LEVEL: "info"
  POOL_SIZE: "10"
  DB_HOST: "postgresql.postgresql.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "messaging_service_db"
  REDIS_HOST: "redis.redis.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "2"

  # Redis Sentinel Configuration
  REDIS_MODE: "sentinel"
  REDIS_SENTINELS: "redis.redis.svc.cluster.local:26379"
  REDIS_MASTER_NAME: "mymaster"
