apiVersion: v1
kind: ServiceAccount
metadata:
  name: messaging-service-sa
  namespace: whispr-prod
  labels:
    app: messaging-service
    app.kubernetes.io/name: messaging-service
    app.kubernetes.io/part-of: whispr
automountServiceAccountToken: true
