---
# VaultDynamicSecret fetches dynamic database credentials from Vault
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: messaging-service-db-creds
  namespace: whispr-prod
spec:
  vaultAuthRef: messaging-service-vault-auth
  mount: database
  path: creds/role-messaging-service
  destination:
    create: true
    name: messaging-service-db-secret
  rolloutRestartTargets:
    - kind: Deployment
      name: messaging-service
  renewalPercent: 67
  revoke: true
