---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: messaging-service-redis-creds
  namespace: whispr-prod
spec:
  vaultAuthRef: messaging-service-vault-auth
  mount: database
  path: creds/redis_role_messaging_service
  destination:
    create: true
    name: messaging-service-redis-secret
  rolloutRestartTargets:
    - kind: Deployment
      name: messaging-service
  renewalPercent: 67
  revoke: true
