apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: whispr-prod
spec:
  selector:
    istio: ingressgateway # --> CRD will configure all pods Gateway which have this label, so this pod will be configured
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - whispr.epitech.beer
        - www.whispr.epitech.beer
        #- api.whispr.epitech.beer
      tls:
        httpsRedirect: true

    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - whispr.epitech.beer
        - www.whispr.epitech.beer
        #- api.whispr.epitech.beer
      tls:
        mode: SIMPLE
        credentialName: istio-gateway-tls
        minProtocolVersion: TLSV1_2

---
apiVersion: networking.istio.io/v1
kind: VirtualService # --> # Define where to route the requests
metadata:
  name: app-routes
  namespace: whispr-prod
spec:
  hosts:
    #- "test.local"
    - whispr.epitech.beer
    - www.whispr.epitech.beer
    # - api.whispr.epitech.beer
  gateways:
    - gateway # VirtualService is attached to the test-gateway without that the traffic will only apply to the mesh (internal traffic)
  http:
    # --> Rules HTTP in order, fist to match win
    # API via whispr.epitech-msc2026.me/api
    - match:
        - uri:
            prefix: "/auth"
          authority:
            exact: whispr.epitech.beer
      route:
        - destination:
            host: auth-service.whispr-prod.svc.cluster.local # by FQDN
            port:
              number: 3001
    - match:
        - uri:
            prefix: "/user"
          authority:
            exact: whispr.epitech.beer
      route:
        - destination:
            host: user-service.whispr-prod.svc.cluster.local
            port:
              number: 3001
    # -> Exemple: http://test.local/api/users → App B

    # WWW redirect --> whispr.epitech-msc2026.me
    - match:
      - uri:
          prefix: /
        authority:
          exact: www.whispr.epitech.beer
      redirect:
        authority: whispr.epitech.beer
        redirectCode: 301

    # Catch all
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: app-a.whispr-prod.svc.cluster.local # by FQDN
            port:
              number: 80

  # --> Exemple: http://test.local/ → App A
  # --> Exemple: http://test.local/index.html → App A
