---
# VaultDynamicSecret fetches dynamic database credentials from Vault
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: media-service-db-creds
  namespace: whispr-prod
spec:
  vaultAuthRef: media-service-vault-auth
  mount: database
  path: creds/role_media_service
  destination:
    create: true
    name: media-service-db-secret
  rolloutRestartTargets:
    - kind: Deployment
      name: media-service
  renewalPercent: 67
  revoke: true
