apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: metrics-cert
  namespace: vault-config-operator-system
spec:
  secretName: vault-config-operator-metrics-service-cert
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - vault-config-operator
  commonName: vault-config-operator-controller-manager-metrics-service.vault-config-operator-system.svc
  dnsNames:
    - vault-config-operator-controller-manager-metrics-service.vault-config-operator-system.svc
    - vault-config-operator-controller-manager-metrics-service.vault-config-operator-system.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer