apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: whispr-staging

resources:
  - ../../base

replicas:
  - name: scheduling-service
    count: 1

images:
  - name: ghcr.io/whispr-messenger/scheduling-service
    newTag: staging

configMapGenerator:
  - name: scheduling-service-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - DB_POOL_SIZE=5

patches:
  - target:
      kind: Deployment
      name: scheduling-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "128Mi"
