apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-config-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  sources:
    # Certificates
    - repoURL: 'https://github.com/whispr-messenger/infrastructure.git'
      targetRevision: main
      path: argocd/k8s/vault-config-operator/certificates

    # Chart
    - repoURL: https://redhat-cop.github.io/vault-config-operator
      chart:  vault-config-operator/vault-config-operator
      targetRevision: v0.8.38
      helm:
        valueFiles:
          - $values/argocd/helm/vault-config-operator/values.yaml

    # Values
    - repoURL: 'https://github.com/whispr-messenger/infrastructure.git'
      targetRevision: main
      ref: values

    # CRs (VaultConnection, VaultAuth)
    - repoURL: 'https://github.com/whispr-messenger/infrastructure.git'
      targetRevision: main
      path: argocd/k8s/vault-config-operator

  destination:
    server: https://kubernetes.default.svc
    namespace: vault-config-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m