# Service configuration
service:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443

# Pod annotations to specify proxy image
_internal_defaults_do_not_set:
  podAnnotations:
    sidecar.istio.io/proxyImage: docker.io/istio/proxyv2:1.24.0

# Resources
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# Autoscaling deactivate for now
autoscaling:
  enabled: false

# Replicas
replicaCount: 2

# Labels
labels:
  app: istio-gateway # Gateway CRD use this label for pod targeting (Kubernetes)
  istio: ingressgateway # Gateway CRD selector (Istio)
