apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: whispr-staging

resources:
  - ../../base

replicas:
  - name: messaging-service
    count: 1

images:
  - name: ghcr.io/whispr-messenger/messaging-service
    newTag: staging

configMapGenerator:
  - name: messaging-service-config
    behavior: merge
    literals:
      - PHX_HOST=staging.whispr.io
      - LOG_LEVEL=debug
      - POOL_SIZE=5

patches:
  - target:
      kind: Deployment
      name: messaging-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
