apiVersion: v2
name: grafana
description: Wrapper chart for Grafana (dependency)
type: application
version: 0.1.0

dependencies:
  - name: grafana
    version: 8.*
    repository: https://grafana.github.io/helm-charts