---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: auth-service-jwt-private
  namespace: whispr-prod
  vaultAuthRef: auth-service-vault-auth
  mount: kv
  type: kv-v2
  path: whispr/auth-service/jwt
  destination:
    name: auth-service-jwt-private-secret
    create: true
  refreshAfter: 1h
