---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: notification-service-public-jwt
  namespace: whispr-prod
spec:
  vaultAuthRef: notification-service-vault-auth
  mount: kv
  type: kv-v2
  path: whispr/shared/jwt
  destination:
    name: notification-service-public-jwt-secret
    create: true
  refreshAfter: 1h
