apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: argocd-auth
  namespace: argocd
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault-admin
    serviceAccount: default
    audiences:
      - https://kubernetes.default.svc.cluster.local
  vaultConnectionRef: argocd-connection
