apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  type: kv-v2
  mount: kv
  path: argocd/secret
  destination:
    name: argocd-secret
    create: true
  refreshAfter: 60s
  vaultAuthRef:
    name: vault-auth
    namespace: vault-secrets-operator-system
