apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: default
  namespace: vault-secrets-operator-system
spec:
  address: http://vault.vault.svc:8200

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: vault-secrets-operator-system
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault-admin
    serviceAccount: default
    audiences:
      - https://kubernetes.default.svc.cluster.local
  vaultConnectionRef:
    name: default
    namespace: vault-secrets-operator-system
