apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduling-service-config
  namespace: whispr-prod
  labels:
    app.kubernetes.io/name: scheduling-service
data:
  NODE_ENV: "production"
  PORT: "3000"
  GRPC_PORT: "3001"
  LOG_LEVEL: "info"
  DB_HOST: "postgresql.postgresql.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "scheduling_service_db"
  DB_TYPE: "postgres"
  REDIS_HOST: "redis.redis.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "5"
