---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: scheduling-service-redis-creds
  namespace: whispr-prod
spec:
  vaultAuthRef: scheduling-service-vault-auth
  mount: database
  path: creds/redis_role_scheduling_service
  destination:
    create: true
    name: scheduling-service-redis-secret
  rolloutRestartTargets:
    - kind: Deployment
      name: scheduling-service
  renewalPercent: 67
  revoke: true
