apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: whispr-prod
data:
  MIX_ENV: "prod"
  PHX_SERVER: "true"
  PORT: "4000"
  LOG_LEVEL: "info"
  POOL_SIZE: "10"
  DB_HOST: "postgresql.postgresql.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "notification_service_db"
