---
# VaultDynamicSecret fetches dynamic Redis credentials from Vault for user-service
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: user-service-redis-creds
  namespace: whispr-prod
spec:
  vaultAuthRef: user-service-vault-auth
  mount: database
  path: creds/redis_role_user_service
  destination:
    create: true
    name: user-service-redis-secret
  rolloutRestartTargets:
    - kind: Deployment
      name: user-service
  renewalPercent: 67
  revoke: true
