---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: scheduling-service-pdb
  namespace: whispr-prod
  labels:
    app.kubernetes.io/name: scheduling-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: scheduling-service
